/* In-device sheets, scroll-edge state and contextual source actions. */
(() => {
 const q=s=>document.querySelector(s);let layer=null,returnFocus=null,selectTarget=null;
 const reduce=()=>matchMedia('(prefers-reduced-motion: reduce)').matches;
 const safe=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 function close(){if(!layer)return;const old=layer;old.inert=true;old.style.pointerEvents='none';layer=null;selectTarget=null;q('#app').inert=false;returnFocus?.setAttribute('aria-expanded','false');if(!reduce())old.querySelector('.app-sheet')?.animate([{transform:'translateY(0)',opacity:1},{transform:'translateY(20%)',opacity:0}],{duration:160}).finished.then(()=>old.remove()).catch(()=>old.remove());else old.remove();if(returnFocus?.isConnected)returnFocus.focus({preventScroll:true});else {const heading=q('#app .app-header');if(heading){heading.tabIndex=-1;heading.focus({preventScroll:true});}}}
 function open(title,content,from){close();returnFocus=from||document.activeElement;layer=document.createElement('div');layer.className='app-sheet-layer';layer.innerHTML=`<button class="sheet-scrim" aria-label="閉じる" tabindex="-1"></button><section class="app-sheet" role="dialog" aria-modal="true" aria-label="${safe(title)}"><span class="sheet-grabber" aria-hidden="true"></span><header><h2>${safe(title)}</h2><button class="sheet-close" aria-label="閉じる">×</button></header>${content}</section>`;q('.phone').append(layer);q('#app').inert=true;layer.querySelector('.sheet-close').onclick=close;layer.querySelector('.sheet-scrim').onclick=close;if(!reduce())layer.querySelector('.app-sheet').animate([{transform:'translateY(100%)'},{transform:'translateY(0)'}],{duration:300,easing:'cubic-bezier(.2,.8,.2,1)'});layer.querySelector('input,button.sheet-close').focus({preventScroll:true});return layer;}
 function sync(select){const trigger=select.nextElementSibling;if(!trigger?.classList.contains('device-select'))return;trigger.querySelector('.select-value').textContent=select.selectedOptions[0]?.textContent||'選択してください';trigger.classList.toggle('is-empty',!select.value);}
 function picker(select,trigger){const title=select.closest('label')?.childNodes[0]?.textContent?.trim()||'選択';const options=[...select.options].map((o,i)=>({value:o.value,text:o.textContent,group:o.parentElement.tagName==='OPTGROUP'?o.parentElement.label:'',index:i}));
 const root=open(title,`${options.length>9?'<label class="sheet-search"><span class="sr-only">候補を検索</span><input type="search" placeholder="候補を検索" aria-label="候補を検索"></label>':''}<div class="sheet-options" role="listbox" aria-label="${safe(title)}"></div>`,trigger);selectTarget=select;trigger.setAttribute('aria-expanded','true');
 function draw(query=''){let group='';root.querySelector('.sheet-options').innerHTML=options.filter(o=>(o.text+o.group).includes(query)).map(o=>{const heading=o.group!==group&&o.group?`<p class="sheet-group">${safe(o.group)}</p>`:'';group=o.group;return `${heading}<button role="option" aria-selected="${o.value===select.value}" data-option-index="${o.index}"><span>${safe(o.text)}</span><span aria-hidden="true">${o.value===select.value?'✓':''}</span></button>`}).join('')||'<p class="sheet-empty">該当する候補がありません。</p>';}
 draw();root.querySelector('input')?.addEventListener('input',e=>draw(e.target.value));root.querySelector('.sheet-options').onclick=e=>{const b=e.target.closest('[data-option-index]');if(!b)return;const value=select.options[Number(b.dataset.optionIndex)].value;close();select.value=value;select.dispatchEvent(new Event('change',{bubbles:true}));sync(select);};}
 function mount(){if(layer)close();if(q('.welcome'))playWelcome();q('#app').querySelectorAll('select').forEach((select,i)=>{if(select.nextElementSibling?.classList.contains('device-select'))return;select.classList.add('device-native-select');select.tabIndex=-1;select.setAttribute('aria-hidden','true');const trigger=document.createElement('button');trigger.type='button';trigger.className='device-select';trigger.setAttribute('role','combobox');trigger.setAttribute('aria-haspopup','dialog');trigger.setAttribute('aria-expanded','false');const label=select.closest('label')?.childNodes[0]?.textContent.trim()||'選択';trigger.setAttribute('aria-label',label);trigger.innerHTML='<span class="select-value"></span><span class="select-chevron" aria-hidden="true">⌄</span>';select.after(trigger);trigger.onclick=e=>{e.preventDefault();e.stopPropagation();picker(select,trigger);};sync(select);});
 const panel=q('#app .app-scroll');const update=()=>q('.app-header')?.classList.toggle('has-scroll',!!panel&&panel.scrollTop>4);update();panel?.addEventListener('scroll',update,{passive:true});
 }
 async function playWelcome(opt={}){const welcome=q('#app .welcome');if(!welcome)return;welcome.querySelector('.launch-splash')?.remove();welcome.classList.add('welcome-launching');const splash=document.createElement('div');splash.className='launch-splash';splash.innerHTML='<div class="launch-brand"><strong>FILTRIP</strong><span>FILTER × TRIP</span></div>';welcome.append(splash);const buttons=[...welcome.querySelectorAll('button')];buttons.forEach(b=>b.disabled=true);const reduced=reduce();try{if(opt.delay&&!reduced)await new Promise(r=>setTimeout(r,opt.delay));await splash.firstElementChild.animate(reduced?[{opacity:0},{opacity:1}]:[{opacity:0,transform:'translateY(24px) scale(.94)',filter:'blur(5px)'},{opacity:1,transform:'translateY(0) scale(1)',filter:'blur(0)'}],{duration:reduced?100:(opt.fadeIn||580),fill:'forwards',easing:'cubic-bezier(.2,.8,.2,1)'}).finished;await new Promise(r=>setTimeout(r,reduced?80:(opt.hold||420)));await splash.animate([{opacity:1},{opacity:0}],{duration:reduced?100:(opt.fadeOut||280),fill:'forwards'}).finished;}catch{}if(!splash.isConnected)return;splash.remove();welcome.classList.remove('welcome-launching');buttons.forEach(b=>b.disabled=false);if(!reduced)welcome.animate([{opacity:0,transform:'translateY(8px)'},{opacity:1,transform:'none'}],{duration:opt.appear||300,easing:'ease-out'});}
 function sourceLink(c){const query=encodeURIComponent((c.providerCreator?.name||c.by)+' '+c.title);if(c.source==='youtube')return 'https://www.youtube.com/results?search_query='+query;if(c.source==='x')return 'https://x.com/search?q='+query;if(c.source==='instagram')return 'https://www.instagram.com/explore/search/keyword/?q='+query;if(c.source==='spotify')return 'https://open.spotify.com/search/'+query;if(c.source==='soundcloud')return 'https://soundcloud.com/search?q='+query;return 'https://www.google.com/search?q='+query;}
 function openSource(c){open(c.type==='動画'?'再生先':c.type==='音楽'?'音楽の配信先':'掲載元',`<div class="source-sheet-body">${thumb(c)}${sourceBadge(c)}<h3>${safe(c.title)}</h3><p>${safe(c.providerCreator?.name||c.by)}</p>${c.original?`<p>${safe(c.desc)}</p>`:`<a class="primary source-destination" href="${safe(sourceLink(c))}" target="_blank" rel="noopener noreferrer">${safe(FILTRIP_PROVIDERS[c.source]||'Web')}でタイトルを検索 ↗</a>`}</div>`);}
 document.addEventListener('change',e=>{if(e.target.tagName==='SELECT')sync(e.target);});
 document.addEventListener('keydown',e=>{if(!layer)return;if(e.key==='Escape'){e.preventDefault();close();return;}if(e.key==='Tab'){const items=[...layer.querySelectorAll('button:not([tabindex="-1"]),input,a[href]')].filter(e=>!e.disabled);const first=items[0],last=items.at(-1);if(e.shiftKey&&document.activeElement===first){e.preventDefault();last.focus();}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first.focus();}}if(['ArrowDown','ArrowUp'].includes(e.key)&&document.activeElement?.matches('[role=option]')){e.preventDefault();const options=[...layer.querySelectorAll('[role=option]')],i=options.indexOf(document.activeElement);options[(i+(e.key==='ArrowDown'?1:-1)+options.length)%options.length].focus();}},true);
 window.FILTRIP_APP_UI={mount,close,openSource,playWelcome};
})();
