/* Content surfaces show publishing accounts; WORLD links only appear in the audience area. */
function sourceBadge(c){if(c.type==='記事'&&!c.original)return '';return `<span class="source-badge source-${escapeHTML(c.source)}" data-source="${escapeHTML(c.source)}"><span class="source-symbol" aria-hidden="true">${({youtube:'▶',instagram:'◎',x:'𝕏',spotify:'≋',soundcloud:'☁',filtrip:'F'})[c.source]||'↗'}</span>${escapeHTML(FILTRIP_PROVIDERS[c.source]||c.source)}</span>`;}
function publisherAvatar(c){const name=c.providerCreator?.name||c.by;if(c.id==='repair')return icon('repairChannel','publisher-avatar');if(['post','snack','play'].includes(c.id))return icon(c.id,'publisher-avatar');return `<span class="publisher-avatar publisher-mark source-${escapeHTML(c.source)}" aria-hidden="true">${escapeHTML(name.replace(/^@/,'').slice(0,2))}</span>`;}
function publisherLine(c,compact=false){return `<span class="publisher-line ${compact?'compact':''}">${publisherAvatar(c)}<span><strong>${escapeHTML(c.providerCreator?.name||c.by)}</strong>${compact?'':`<small>${escapeHTML(c.providerCreator?.handle||({youtube:'動画チャンネル',instagram:'Instagram',x:'X',spotify:'アーティスト',soundcloud:'アーティスト',filtrip:'FILTRIP ORIGINAL',web:'記事の発行元'})[c.source]||'')}</small>`}</span></span>`;}
function postPreview(c){return `<div class="social-preview social-${escapeHTML(c.source)}">${publisherLine(c)}<button class="social-body" data-action="detail" data-id="${c.id}"><span>${escapeHTML(c.desc)}</span>${c.curated?`<span class="social-image">${thumb(c)}</span>`:''}</button></div>`;}
function audiencePanel(c){if(state.detailOrigin.kind==='external-archive')return `<section class="audience-panel"><h3>保存したコンテンツ</h3><p>${escapeHTML(savedOriginLabel(state.detailOrigin))}</p></section>`;return `<section class="audience-panel"><h3>このコンテンツを好きな人</h3><div class="audience-count">${functionalIcon('people')}<span>このWORLDの <b>${worldCount(c,state.detailOrigin)}</b> / ${state.detailOrigin.members} 人</span></div><div class="audience-links"><button class="mini-link" data-action="why-current">好きのつながりを見る ›</button><button class="mini-link" data-action="detail-likers" data-id="${c.id}">好きな人を見る ›</button></div></section>`;}
function renderContentDetail(c,kind){
 const source=FILTRIP_PROVIDERS[c.source]||'掲載元';
 const sourceButton=c.original?'':`<button class="source-open-button" data-action="source-open" data-id="${c.id}">${escapeHTML(c.source==='web'?'掲載元':source)}で探す <span aria-hidden="true">↗</span></button>`;
 const active=state.detailSection||'search';
 let body='';
 if(kind==='video')body=`<div class="video-player" data-player-id="${c.id}">${thumb(c)}<button class="player-play" data-action="source-open" data-id="${c.id}" aria-label="${escapeHTML(c.title)}の再生先を表示"><span aria-hidden="true">▶</span></button><div class="player-bottom"><span>${escapeHTML(c.duration||'動画')}</span>${sourceBadge(c)}<span class="player-expand" aria-hidden="true">⛶</span></div></div><h2 class="detail-title">${escapeHTML(c.title)}</h2>${publisherLine(c)}<p class="detail-description">${escapeHTML(c.desc)}</p>${sourceButton}${audiencePanel(c)}${relatedSection(c)}`;
 if(kind==='post')body=`<article class="social-detail social-${escapeHTML(c.source)}">${publisherLine(c)}<p class="social-text">${escapeHTML(c.desc)}</p>${c.curated?`<div class="social-image">${thumb(c)}</div>`:''}<div class="social-origin">${sourceBadge(c)}<span>${escapeHTML(c.publishedLabel||'3時間前')}</span></div><div class="social-stats"><button data-action="like" aria-pressed="${state.liked.includes(c.id)}">${functionalIcon('heart')}<span>${c.n*4+3+(state.liked.includes(c.id)?1:0)}</span></button><span>コメント ${c.reply?1:0}</span></div>${c.reply?`<section class="social-reply"><strong>おやつの記録</strong><p>${escapeHTML(c.reply)}</p></section>`:''}${sourceButton}</article>${audiencePanel(c)}`;
 if(kind==='article')body=`<article class="reading-detail"><div class="article-hero">${thumb(c)}</div><div class="article-meta">${sourceBadge(c)}<span>読みもの · ${Math.max(1,Math.ceil((Array.isArray(c.body)?c.body.join(''):c.body||c.desc).length/450))}分</span></div><h2 class="detail-title">${escapeHTML(c.title)}</h2>${publisherLine(c)}<div class="reading-body">${(Array.isArray(c.body)?c.body:[c.body||c.desc]).map(p=>`<p>${escapeHTML(p)}</p>`).join('')}</div>${sourceButton}</article>${audiencePanel(c)}`;
 if(kind==='music')body=`<section class="listening-detail"><div class="album-art">${thumb(c)}</div>${sourceBadge(c)}<h2 class="detail-title">${escapeHTML(c.title)}</h2><p class="artist-name">${escapeHTML(c.providerCreator?.name||c.by)}</p><button class="music-play" data-action="source-open" data-id="${c.id}"><span aria-hidden="true">▶</span> 再生先を見る</button><p class="detail-description">${escapeHTML(c.desc)}</p></section>${audiencePanel(c)}${relatedSection(c)}`;
 return shell(({video:'動画を見る',post:'投稿を見る',article:'記事を読む',music:'音楽を聴く'})[kind],body,{active,foot:addButton(c),className:'content-detail detail-'+kind});
}
